#!/bin/bash
#
# stoned        Starts stone daemon.
#
# chkconfig: 2345 99 25
# description: Stone is a TCP/IP repeater in the application layer. \
# It repeats TCP and UDP from inside to outside of a firewall, or \
# from outside to inside.

### BEGIN INIT INFO
# Provides: stoned
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Should-Start: $syslog
# Should-Stop: $syslog
# Default-Start: 2345
# Default-Stop: 99
# Short-Description: Starts/stop the "stone" daemon
# Description:      Stone is a TCP/IP repeater in the application layer.
#    It repeats TCP and UDP from inside to outside of a firewall, or
#    from outside to inside.
### END INIT INFO

# source function library.
. /etc/init.d/functions

RETVAL=0
prog=stone
lockfile=/var/lock/subsys/$prog
STONE_BIN="/usr/bin/$prog"
STONE_CONF="/etc/${prog}d.conf"
STONE_CHROOT=/var/chroot/stoned
STONE_OPTS="-l -C $STONE_CONF -o stoned -g stoned -t $STONE_CHROOT"
PIDFILE=/var/run/${prog}.pid

start()
{
  [ "$EUID" != "0" ] && exit 4
  echo -n $"Starting $prog: "
  daemon $STONE_BIN $STONE_OPTS -D -i $PIDFILE
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch $lockfile
  return $RETVAL
}

stop()
{
  [ "$EUID" != "0" ] && exit 4
  echo -n $"Shutting down $prog: "
  killproc -p $PIDFILE $STONE_BIN
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $lockfile
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status $prog
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac

exit $RETVAL
